baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Hugo Boilerplate'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = 'boilerplate'

# Output formats configuration
[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["txt"]
  [mediaTypes."application/xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.ROBOTS]
    mediaType = "text/plain"
    baseName = "robots"
    isPlainText = true
    notAlternative = true
    permalinkable = true
  [outputFormats.SITEMAP]
    mediaType = "application/xml"
    baseName = "sitemap"
    isPlainText = false
    isHTML = false
    noUgly = true
    rel = "sitemap"

# Site parameters
[params]
  description = "A clean Hugo boilerplate"
  author = "Your Name"
  mainSections = ["blog"]
  dateFormat = "January 2, 2006"

# Language configuration
[languages]
  [languages.en]
    languageName = "English"
    title = "English Site Title"
    weight = 1
    contentDir = "content/en"
    baseURL = "https://example.com"
    bcp47Lang = "en-us"
    [languages.en.params]
      description = "English site description"
    [[languages.en.menu.main]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "blog"
      name = "Blog"
      url = "/blog/"
      weight = 2

  [languages.de]
    languageName = "Deutsch"
    title = "Deutsche Site Title"
    weight = 2
    contentDir = "content/de"
    baseURL = "https://example.de"
    bcp47Lang = "de"
    [languages.de.params]
      description = "Deutsche Seitenbeschreibung"
    [[languages.de.menu.main]]
      identifier = "home"
      name = "Startseite"
      url = "/"
      weight = 1
    [[languages.de.menu.main]]
      identifier = "blog"
      name = "Beiträge"
      url = "/blog/"
      weight = 2

  [languages.sk]
    languageName = "Slovensky"
    title = "Slovenská stránka"
    weight = 3
    contentDir = "content/sk"
    baseURL = "https://example.sk"
    bcp47Lang = "sk"
    [languages.sk.params]
      description = "Slovenská stránka popis"
    [[languages.sk.menu.main]]
      identifier = "home"
      name = "Domov"
      url = "/"
      weight = 1
    [[languages.sk.menu.main]]
      identifier = "blog"
      name = "Články"
      url = "/blog/"
      weight = 2

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Build settings
[build]
  writeStats = true

# Multilingual settings
[sitemap]
  filename = "sitemap.xml"
