# Output formats configuration
[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["txt"]
  [mediaTypes."application/xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.ROBOTS]
    mediaType = "text/plain"
    baseName = "robots"
    isPlainText = true
    notAlternative = true
    permalinkable = true
  [outputFormats.SITEMAP]
    mediaType = "application/xml"
    baseName = "sitemap"
    isPlainText = false
    isHTML = false
    noUgly = true
    rel = "sitemap"